// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// bandsolve
List bandsolve(NumericMatrix D, int l, int u, NumericVector b, bool sym);
RcppExport SEXP bandsolve_bandsolve(SEXP DSEXP, SEXP lSEXP, SEXP uSEXP, SEXP bSEXP, SEXP symSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type l(lSEXP);
    Rcpp::traits::input_parameter< int >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< bool >::type sym(symSEXP);
    __result = Rcpp::wrap(bandsolve(D, l, u, b, sym));
    return __result;
END_RCPP
}
// LDL
List LDL(NumericMatrix D);
RcppExport SEXP bandsolve_LDL(SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type D(DSEXP);
    __result = Rcpp::wrap(LDL(D));
    return __result;
END_RCPP
}
// LDU
List LDU(NumericMatrix D, int l, int u);
RcppExport SEXP bandsolve_LDU(SEXP DSEXP, SEXP lSEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type l(lSEXP);
    Rcpp::traits::input_parameter< int >::type u(uSEXP);
    __result = Rcpp::wrap(LDU(D, l, u));
    return __result;
END_RCPP
}
