# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @description Fast inplace solver for linears systems involving band matrix.
#' @title fastbandsolve
#' @param D Rotated row-wised matrix.
#' @name bandsolve
#' @param b Right hand side of the linear system
#' @return List with components with the solution of the linear system and the rotated matrixes L and U.
#' @examples n=2000;
#' D0=3+runif(n);
#' D1=-0.2*runif(n-1);
#' D=cbind(D0,c(D1,0))
#' b=runif(n)
#' sol=fastbandsolve(D,b,l=1,u=0)
NULL

fastbandsolve <- function(D, b) {
    .Call('bandsolve_fastbandsolve', PACKAGE = 'bandsolve', D, b)
}

#' @description Fast inplace solver for linears systems involving band matrix.
#' @title fastbandsolve
#' @param D Rotated row-wised matrix.
#' @name bandsolve
#' @param b Right hand side of the linear system
#' @return List with components with the solution of the linear system and the rotated matrixes L and U.
#' @examples n=2000;
#' D0=3+runif(n);
#' D1=-0.2*runif(n-1);
#' D=cbind(D0,c(D1,0))
#' b=runif(n)
#' sol=fastbandsolve(D,b,l=1,u=0)
NULL

fastbandsolveMatrix <- function(D, B) {
    .Call('bandsolve_fastbandsolveMatrix', PACKAGE = 'bandsolve', D, B)
}

#' @description Fast inplace LDL decomposition of symmetric band matrix of length k.
#' @title LDL
#' @param D Rotated row-wised matrix of dimensions n*k, with first column corresponding to the diagonal, the second to the first super-diagonal and so on.
#' @return List with D as solution of our LDL decomposition.
#' @name LDL
#' @examples n=2000;
#' D0=3+runif(n);
#' D1=-0.2*runif(n-1);
#' D=cbind(D0,c(D1,0))
#' sol=LDL(D)
#' @export
NULL

LDL <- function(D) {
    .Call('bandsolve_LDL', PACKAGE = 'bandsolve', D)
}

#' @description Fast inplace LDU decomposition of band matrix.
#' @title LDU
#' @param D Rotated row-wised matrix of dimensions n*(l+1+u), where the l first column corresponding to the sub-diagonal elements, the column l+1 corresponding to the diagonal and the u next to the super-diagonal elements.
#' @param l Lower bandwidth.
#' @param u Upper bandwidth.
#' @name LDU
#' @return List with D as solution of our LDU decomposition.
#' @examples n=2000;
#' D0=0.3*runif(n-1);
#' D1=3+runif(n);
#' D2=-0.2*runif(n-1);
#' D3=runif(n-2)
#' D=cbind(c(D0,0),D1,c(D2,0),c(D3,0,0))
#' res=LDU(D,l=1,u=2)
NULL

LDU <- function(D, l, u) {
    .Call('bandsolve_LDU', PACKAGE = 'bandsolve', D, l, u)
}

