# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bandsolve_cpp <- function(D, B) {
    .Call('bandsolve_bandsolve_cpp', PACKAGE = 'bandsolve', D, B)
}

#' @description Fast inplace LDL decomposition of symmetric band matrix of length k.
#' @title LDL
#' @param D Rotated row-wised matrix of dimensions n*k, with first column corresponding to the diagonal, the second to the first super-diagonal and so on.
#' @return List with D as solution of our LDL decomposition.
#' @name LDL
#' @examples 
#' 
#' n=10;
#' D0=1:10;
#' D1=exp(-c(1:9));
#' D=cbind(D0,c(D1,0))
#' sol=LDL(D)
#' @export
NULL

LDL <- function(D) {
    .Call('bandsolve_LDL', PACKAGE = 'bandsolve', D)
}

